---

- name: Docker host setup
  hosts: docker_host
  become: yes
  roles:
    - role: oefenweb.ssh_client
      tags:
        - ssh
        - client
    - role: willshersystems.sshd
      tags:
        - ssh
        - server

    - role: docker
      tags:
        - docker
        - server
  tasks:
    - name: Make ssh directory
      file:
        path: "/home/ansible/.ssh/"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0700
        state: directory
      tags:
        - ssh
        - keys

    - name: Install ssh keys for ansible user
      assemble:
        src: "files/keys/"
        dest: "/home/ansible/.ssh/authorized_keys"
        remote_src: no
        owner: 1000
        group: 100
        mode: 0644
      tags:
        - ssh
        - keys

    - name: Install additional ssh packages
      apk:
        name:
          - openssh-server-pam
          - openssh-sftp-server
          - python3
          - iputils
      when: ansible_facts['os_family'] == "Alpine"

    - name: "Install RedHat specific items"
      block:
        - name: Install virtualization packages
          ansible.builtin.dnf:
            name: "@Virtualization Hypervisor"
            state: present

        - name: Start/enable libvirtd service
          service:
            name: libvirtd
            state: started
            enabled: true

        - name: Enable ansible user for libvirt managment
          ansible.builtin.user:
            name: ansible
            append: yes
            groups: libvirt
      when: ansible_facts['os_family'] == "RedHat"
