---
#
# Required roles for project
# install with: ansible-galaxy install -r requirements.yml
#
collections:
    - name: containers.podman
      source: https://galaxy.ansible.com

roles:
    - name: willshersystems.sshd
    - name: oefenweb.ssh_client
    - name: darrylweaver.samba
    - name: ahuffman.resolv
    - name: idiv-biodiversity.systemd_resolved
