#
# Required roles for project
# install with: ansible-galaxy install -r requirements.yml
#
- src: willshersystems.sshd
- src: oefenweb.ssh_client
- src: darrylweaver.samba
- src: ahuffman.resolv
- src: idiv-biodiversity.systemd_resolved
- src: geerlingguy.nfs
