---

- name: server setup
  hosts: all
  vars:

  roles:
    - role: oefenweb.ssh_client
      tags:
        - ssh
        - client
    - role: willshersystems.sshd
      tags:
        - ssh
        - server

  # tasks:
  #   - name: Test if tasks work in roles
  #     authorized_key:
  #       user: "{{ item }}"
  #       key: "files/{{ item }}.pub"
  #       state: present
  #     loop:
  #       - "brian"
  #     tags:
  #       - ssh
  #       - client
  #       - keys
