---
#
# Required roles for project
# install with: ansible-galaxy install -r requirements.yml
#
collections:
    - name: containers.podman
      source: https://galaxy.ansible.com

roles:
    - src: willshersystems.sshd
      version: "v0.12.0"
    - src: oefenweb.ssh_client
      verison: "1.1.12"
    - src: darrylweaver.samba
      version: "b0bdc04599a92edcbbb3849cc036b71b911515fe"
    - src: ahuffman.resolv
      version: "1.3.2"
    - src: idiv-biodiversity.systemd_resolved
      version: "v1.0.3"
