---

- name: Create skeleton directory structure
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "users"
    mode: 0750
    state: directory
  loop:
    - "{{ docker_root }}/{{ inventory_hostname }}/"
    - "{{ docker_root }}/{{ inventory_hostname }}/config"
    - "{{ docker_root }}/{{ inventory_hostname }}/data"

- name: Deploy container
  copy:
    src: "{{ item }}"
    dest: "{{ docker_root }}/{{ inventory_hostname }}/container/"
    owner: "{{ ansible_user }}"
    group: "users"
    mode: 0640
  with_fileglob:
    - "container/*"
  notify: Build container

- name: Copy in run script
  template:
    src: "run.sh.j2"
    dest: "{{ docker_root }}/{{ inventory_hostname }}/run.sh"
    owner: "{{ ansible_user }}"
    group: "users"
    mode: 0750
  notify: Run container

- name: Include build tasks
  include_tasks: "build.yml"
  tags:
    - never
    - build
