---

- name: Set facts - define docker_role_path
  set_fact:
    d_role_path: "{{ role_path }}"

- name: include skeleton role
  include_role:
    name: docker_skeleton
  vars:
    docker_role_path: "{{ d_role_path }}"

- name: Set SELinux context for base git dir
  sefcontext:
    target: "{{ git_base_dir }}(/.*)?"
    setype: container_file_t
    state: present

- name: Create keys
  assemble:
    src: "files/keys/"
    dest: "{{ docker_root }}/{{ inventory_hostname }}/authorized_keys"
    remote_src: no
    owner: 1000
    group: 100
    mode: 0644
