---

- name: Include Docker skeleton file
  include: "../docker_skel/tasks.yml"

- name: Create git path
  file:
    path: "{{ docker_root }}/{{ inventory_hostname }}/git"
    owner: 1000
    group: 100
    mode: 0755
    state: directory

- name: Create keys
  assemble:
    src: "files/keys/"
    dest: "{{ docker_root }}/{{ inventory_hostname }}/authorized_keys"
    remote_src: no
    owner: 1000
    group: 100
    mode: 0640
