---

docker_ip: "{{ hosts.ip4['nfs.milco.info'] }}"

docker_options:
  - "--privileged"

docker_ports:
  - "2049:2049"
  - "111:111"
  - "20048:20048"

docker_volumes:
  - host_path: "{{ docker_root }}/{{ inventory_hostname }}/config/exports"
    container_path: "/etc/exports"
    type: "file"
  - host_path: "{{ docker_root }}/{{ inventory_hostname }}/shares"
    container_path: "/srv/shares"
    type: "directory"

docker_image: "{{ inventory_hostname }}:latest"

nfs_exports:
  - share: "/srv/shares"
    hosts:
      - name: "*"
        options:
          - "rw"
          - "sync"
          - "no_root_squash"
          - "insecure"
