---
# handlers file for ansible-samba
- name: restart nmbd
  service:
    name: "nmbd"
    state: restarted
  when: not samba_server_role == "active directory domain controller"

- name: restart samba-ad-dc
  service:
    name: "samba-ad-dc"
    state: restarted
  when: samba_server_role == "active directory domain controller"

- name: restart smbd
  service:
    name: "smbd"
    state: restarted
