---

docker_options:
  - "-e SSH_USERS=git:1000"

docker_ports:
  - "80:8080"
  - "50000:50000"

docker_socket_path: "{{ '/run/docker.sock' if ansible_facts['os_family'] == 'RedHat' else '/var/run/docker.sock' }}"


docker_volumes:
  - host_path: "{{ docker_root }}/{{ inventory_hostname }}/data"
    container_path: "/var/jenkins_home"
    type: "directory"
  - host_path: "{{ docker_socket_path }}"
    container_path: "/var/run/docker.sock"
    type: "file"
