---

docker_ip: "{{ hosts[ (inventory_hostname_short) ].ip4 }}"

docker_options:
  - "--privileged"
  - "-e 'DOMAIN={{ local.dns_domain }}'"
  - "-e 'NETBIOS={{ local.netbios_domain }}'"
  - "-e 'DOMAINPASS={{ ad_admin_password }}'"
  - "-e 'DNSFORWARDER=192.168.1.1'"
  - "-e 'HOSTIP=192.168.1.10'"
  - "--dns-search {{ local.dns_domain }}"
  - "--dns {{ hosts.ad1.ip4 }}"
  - "--dns {{ hosts.ad2.ip4 }}"
  - "--add-host ad1.n.milco.info:192.168.1.10"
  - "--add-host ad2.n.milco.info:192.168.1.11"

docker_ports:
  - "53:53"
  - "53:53/udp"
  - "88:88"
  - "88:88/udp"
  - "135:135"
  - "137-138:137-138/udp"
  - "139:139"
  - "389:389"
  - "389:389/udp"
  - "445:445"
  - "464:464"
  - "464:464/udp"
  - "636:636"
  - "1024-1044:1024-1044"
  - "3268-3269:3268-3269"

docker_volumes:
  - host_path: "/etc/localtime"
    container_path: "/etc/localtime:ro"
    type: "file"
  - host_path: "{{ docker_root }}/{{ inventory_hostname }}/data/"
    container_path: "/var/lib/samba"
    type: "directory"
  - host_path: "{{ docker_root }}/{{ inventory_hostname }}/config/samba"
    container_path: "/etc/samba/external"
    type: "directory"

docker_image: "{{ inventory_hostname }}:latest"
