---

- name: Set facts - define docker_role_path
  set_fact:
    d_role_path: "{{ role_path }}"

- name: include skeleton role
  include_role:
    name: docker_skeleton
  vars:
    docker_role_path: "{{ d_role_path }}"

- name: Start podman
  service:
    name: podman.socket
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"
