---

- name: Set facts - define docker_role_path
  set_fact:
    d_role_path: "{{ role_path }}"

- name: include skeleton role
  include_role:
    name: docker_skeleton
  vars:
    docker_role_path: "{{ d_role_path }}"

- name: Include encrypted variables
  include_vars: "vault.backups.yml"

- name: generate setup.json
  template:
    src: setup.json.j2
    dest: "{{ docker_root }}/{{ inventory_hostname }}/container/setup.json"

- name: generate init script
  template:
    src: init.sh.j2
    dest: "{{ docker_root }}/{{ inventory_hostname }}/container/init.sh"
