---

- name: Include Docker skeleton file
  include: "../docker_skel/tasks.yml"

- name: Create exports file
  template:
    src: exports.j2
    dest: "{{ docker_root }}/{{ docker_name }}/config/exports"
    owner: "{{ ansible_user }}"
    group: "users"
    mode: 0640
