---

- name: Include Docker skeleton role
  include_role:
    name: "docker_skeleton"

- name: Create exports file
  template:
    src: exports.j2
    dest: "{{ docker_root }}/{{ inventory_hostname }}/config/exports"
    owner: "{{ ansible_user }}"
    group: "users"
    mode: 0640
  notify: Run container

- name: Create exports directories
  file:
    path: "{{ item.host_path }}"
    owner: "{{ ansible_user }}"
    group: "users"
    mode: 0750
    state: "{{ item.type }}"
  loop: "{{ docker_volumes }}"
