---

docker_ports:
  - 2049:2049
  - 111:111
  - 20048:20048

nfs_exports:
  - share: "/srv/shares"
    hosts:
      - name: "*"
        options:
          - "rw"
          - "sync"
          - "no_root_squash"
          - "insecure"
