---
- name: Set facts - define docker_role_path
  set_fact:
    d_role_path: "{{ role_path }}"

- name: include skeleton role
  include_role:
    name: docker_skeleton
  vars:
    docker_role_path: "{{ d_role_path }}"

- name: get nginx container
  containers.podman.podman_container:
    name: basic-webserver
    image: registry.access.redhat.com/ubi8/nginx-118
    state: started
    recreate: yes
    ports:
      - "80:8080"
    volume:
      - "/srv/web/html:/usr/share/nginx/html"
      - "/srv/web/logs:/var/log/nginx"
