network:
  version: 2
  ethernets:
    enp1s0:
      addresses:
      {% for ip in networking.ip4 %}
  - "{{ ip }}/24"
      {% endfor %}{% for ip6 in networking.ip6 %}
  - "{{ ip6 }}/128"
      {% endfor %}

      gateway4: "{{ local.gateway }}"
      nameservers:
          search:
            - "{{ local.dns_domain }}"
          addresses:
          {% for resolver4 in local.external_resolvers_ipv4 %}
  - "{{ resolver4 }}"
          {% endfor %}{% for resolver6 in local.external_resolvers_ipv6 %}
  - "{{ resolver6 }}"
          {% endfor %}
