---

- name: Add community repo to package management
  copy:
    src: files/apk.repo
    dest: /etc/apk/repositories
    owner: root
    group: root
    mode: 0644

- name: Install docker and vim
  apk:
    name:
      - docker
      - vim
    state: latest
    update_cache: yes

- name: Start docker service
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Add ansible user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: 'docker'
    append: yes

- name: Configure interfaces for networking
  template:
    src: "interfaces.j2"
    dest: "/etc/network/interfaces"
    owner: root
    group: root
    mode: 0644

- name: restart networking
  service:
    name: networking
    state: restarted
