---

- name: remove unneeded packages
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: update all packages
  apt:
    name: "*"
    state: latest

- name: install apt packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: download repo key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/gpg.key

- name: install repo key
  command: "apt-key add /tmp/gpg.key"

- name: add repo
  command: "add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'"

- name: install needed packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
