---

- name: server setup
  hosts: ad_dc
  remote_user: ansible
  become: yes
  vars:
    samba_ad_info:
      ad_dc_hostname: '{{ ansible_hostname }}'
      ad_dns_domain_name: '{{ local.dns_domain }}'
      adminpass: '{{ ad_admin_password }}'
      backend_dns: SAMBA_INTERNAL
      dns_forwarder: "{{ local.external_resolvers_ipv4|join(' ') }} {{ local.external_resolvers_ipv6|join(' ') }}"
      kerberos_realm: '{{ local.dns_domain }}'
      netbios_domain_name: "{{ local.netbios_domain }}"
    samba_interfaces: "{{ ansible_default_ipv4.address|default('') }} {{ ansible_default_ipv6.address|default('') }} lo"
    samba_bind_interfaces_only: yes
    samba_workgroup: "{{ local.netbios_domain }}"
    samba_create_domain_controller: true
    samba_security: ADS
    samba_server_role: 'active directory domain controller'

    samba_domain_users: []
    samba_shares: []

    sshd: global_sshd
    ssh_client_configurations: global_ssh_client_configurations
  roles:
    - role: willshersystems.sshd
      tags:
        - ssh
        - sshd
        - server
    - role: oefenweb.ssh_client
      tags:
        - ssh
        - client

    - role: darrylweaver.samba
      tags: ad_dc
