---

- name: Docker host setup
  hosts: vm_host
  become: yes
  roles:
    - role: oefenweb.ssh_client
      tags:
        - ssh
        - client
    - role: willshersystems.sshd
      tags:
        - ssh
        - server

    - role: docker
      tags:
        - docker
        - server
