---

- name: Docker host setup
  hosts: docker_host
  become: yes
  roles:
    - role: oefenweb.ssh_client
      tags:
        - ssh
        - client
    - role: willshersystems.sshd
      tags:
        - ssh
        - server

    - role: docker
      tags:
        - docker
        - server
  tasks:
    - name: Install additional ssh packages
      apk:
        name:
          - openssh-server-pam
          - openssh-sftp-server
          - python3
      when: ansible_os_family == "Alpine"
