---

- name: Build container
  command: "docker build -t {{ inventory_hostname }} ."
  args:
    chdir: "{{ docker_root }}/{{ inventory_hostname }}/container"
  when: does_dockerfile.stat.exists == true
  notify:
    - Run container
  tags:
    - never
    - build

- name: Run container
  command: "{{ docker_root }}/{{ inventory_hostname }}/run.sh"
  tags:
    - never
    - build
