---

- name: install systemd
  pacman:
    name: systemd
    state: present

- name: configure systemd-resolved
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644
  register: systemd_resolved_configuration

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
  when: systemd_resolved_configuration.changed

- name: enable systemd-resolved service and assure it is started
  systemd:
    name: systemd-resolved
    enabled: yes
    state: started

- name: link /etc/resolv.conf to stub
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link

...
