---

- name: Configure ssh client - authentication
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: 'GSSAPIAuthentication'
    line: "GSSAPIAuthentication yes"
- name: Configure ssh client - delegate
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: 'GSSAPIDelegateCredentials'
    line: "GSSAPIDelegateCredentials yes"
- name: Configure ssh client - key exchange
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: 'GSSAPIKeyExchange'
    line: "GSSAPIKeyExchange yes"

- name: Create users
  user:
    name: "{{ item.key }}"
    update_password: "{{ item.value.update_password }}"
    password: "{{ item.value.password }}"
    append: "{{ item.value.append }}"
    comment: "{{ item.value.description }}"
    group: "{{ item.value.group }}"
    groups: "{{ item.value.groups }}"
    state: "{{ item.value.state }}"
    shell: "{{ item.value.shell }}"
    system: "{{ item.value.system }}"
    create_home: "{{ item.value.create_home }}"
    home: "{{ item.value.home }}"
  with_dict: "{{ users }}"

- name: Create .ssh folder
  file:
    path: "{{ item.value.home }}/.ssh"
    state: directory
    owner: "{{ item.key }}"
    group: "{{ item.value.group }}"
    mode: 0700
  with_dict: "{{ users }}"

- name: Add keyfile for users
  template:
    src: "{{ item.value.key_file }}"
    dest: "{{ item.value.home }}/.ssh/authorized_keys"
    owner: "{{ item.key }}"
    group: "{{ item.value.group }}"
    mode: 0600
  with_dict: "{{ users }}"

- name: Copy sshd config
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
